### ISSUE TITLE
"$POSTINSTALL" was unexpected at this time.

### ISSUE THREAD

**Issue by luanad6365** [GetAmbassador/react-ions#334]
Hello,

I have currently tried install react-ions package and getting the issue as on title..
Error detail from console output:

```
D:\project\dmdc\manage-category>npm install react-ions --save
npm WARN prefer global marked@0.3.6 should be installed with -g

> react-ions@1.0.1 postinstall D:\project\dmdc\manage-category\node_modules\react-ions
> if [ "$POSTINSTALL" = true ]; then npm run build:server; else echo 0; fi

"$POSTINSTALL" was unexpected at this time.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"an
y"} (current: {"os":"win32","arch":"x64"})
npm WARN react-ions@1.0.1 requires a peer of react@~15.1.0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "react-ions" "--save"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! react-ions@1.0.1 postinstall: `if [ "$POSTINSTALL" = true ]; then npm run build:server; else echo 0; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-ions@1.0.1 postinstall script 'if [ "$POSTINSTALL" = true ]; then npm run build:server; els
e echo 0; fi'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-ions package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if [ "$POSTINSTALL" = true ]; then npm run build:server; else echo 0; fi
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-ions
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-ions
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\project\dmdc\manage-category\npm-debug.log

D:\project\dmdc\manage-category>node --v
node: bad option: --v

D:\project\dmdc\manage-category>node -v
v6.9.2

D:\project\dmdc\manage-category>

```

Please find below detail from the npm-debug.log:
```
21205 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
21206 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
21207 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
21207 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
21207 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
21207 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
21208 warn react-ions@1.0.1 requires a peer of react@~15.1.0 but none was installed.
21209 verbose If you need help, you may report this error at:
21209 verbose     <https://github.com/npm/npm/issues>
21210 verbose stack Error: react-ions@1.0.1 postinstall: `if [ "$POSTINSTALL" = true ]; then npm run build:server; else echo 0; fi`
21210 verbose stack Exit status 1
21210 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
21210 verbose stack     at emitTwo (events.js:106:13)
21210 verbose stack     at EventEmitter.emit (events.js:191:7)
21210 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
21210 verbose stack     at emitTwo (events.js:106:13)
21210 verbose stack     at ChildProcess.emit (events.js:191:7)
21210 verbose stack     at maybeClose (internal/child_process.js:877:16)
21210 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
21211 verbose pkgid react-ions@1.0.1
21212 verbose cwd D:\project\dmdc\manage-category
21213 error Windows_NT 6.1.7601
21214 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-ions" "--save"
21215 error node v6.9.2
21216 error npm  v3.10.9
21217 error code ELIFECYCLE
21218 error react-ions@1.0.1 postinstall: `if [ "$POSTINSTALL" = true ]; then npm run build:server; else echo 0; fi`
21218 error Exit status 1
21219 error Failed at the react-ions@1.0.1 postinstall script 'if [ "$POSTINSTALL" = true ]; then npm run build:server; else echo 0; fi'.
21219 error Make sure you have the latest version of node.js and npm installed.
21219 error If you do, this is most likely a problem with the react-ions package,
21219 error not with npm itself.
21219 error Tell the author that this fails on your system:
21219 error     if [ "$POSTINSTALL" = true ]; then npm run build:server; else echo 0; fi
21219 error You can get information on how to open an issue for this project with:
21219 error     npm bugs react-ions
21219 error Or if that isn't available, you can get their info via:
21219 error     npm owner ls react-ions
21219 error There is likely additional logging output above.
21220 verbose exit [ 1, true ]
```

**Comment by Chochek** [comment]
@luanad6365 you can remove or comment out the [postinstall command](https://github.com/GetAmbassador/react-ions/blob/master/package.json#L35) in package.json for now until we figure out what the problem is. It's not important when setting up locally.

**Comment by luanad6365** [comment]
@Chochek could you plz remove "postinstall command" in your package.json, so I can install react-ions via npm package, I want use this for my currently project. Thank you !

**Comment by Chochek** [comment]
@luanad6365 yes, it will be removed soon - https://github.com/GetAmbassador/react-ions/pull/335

**Comment by luanad6365** [comment]
Yeah, hope that pull request will be merged soon, so I can continue my project. Thanks again @Chochek

**Comment by Chochek** [comment]
@luanad6365 the new version (1.0.2) is released. Please try installing again

**Comment by luanad6365** [comment]
@Chochek I install succeeded, but unfortunately still can't use your package. I tried simple component
```
import React from 'react'
import Button from 'react-ions/lib/Button'

const ExampleButtonDefault = () => (
  <Button>I am a Button</Button>
)

export default ExampleButtonDefault
```

But error thrown

```
./~/react-ions/lib/components/Button/style.scss
Module parse failed: D:\project\dmdc\manage-category\node_modules\react-ions\lib\components\Button\style.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
```

This is my package.json
```
{
  "name": "material-ui-example-webpack",
  "version": "0.16.4",
  "description": "Sample project that uses Material-UI",
  "repository": {
    "type": "git",
    "url": "https://github.com/callemall/material-ui.git"
  },
  "scripts": {
    "start": "webpack-dev-server --config webpack-dev-server.config.js --progress --inline --colors",
    "build": "webpack --config webpack-production.config.js --progress --colors"
  },
  "private": true,
  "devDependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.8",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-2": "^6.18.0",
    "html-webpack-plugin": "^2.24.1",
    "transfer-webpack-plugin": "^0.1.4",
    "webpack": "^1.13.3",
    "webpack-dev-server": "^1.16.2"
  },
  "dependencies": {
    "material-ui": "^0.16.4",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-edit-inline": "^1.0.8",
    "react-highlight": "^0.9.0",
    "react-ions": "^1.0.2",
    "react-tap-event-plugin": "^2.0.1",
    "react-ultimate-pagination": "^0.9.0",
    "riek": "^1.0.7"
  }
}
```

And webpack

```
const webpack = require('webpack');
const path = require('path');
const buildPath = path.resolve(__dirname, 'build');
const nodeModulesPath = path.resolve(__dirname, 'node_modules');
const TransferWebpackPlugin = require('transfer-webpack-plugin');

const config = {
  // Entry points to the project
  entry: [
    'webpack/hot/dev-server',
    'webpack/hot/only-dev-server',
    path.join(__dirname, '/src/app/app.js'),
  ],
  // Server Configuration options
  devServer: {
    contentBase: 'src/www', // Relative directory for base of server
    devtool: 'eval',
    hot: true, // Live-reload
    inline: true,
    port: 3000, // Port Number
    host: 'localhost', // Change to '0.0.0.0' for external facing server
  },
  devtool: 'eval',
  output: {
    path: buildPath, // Path of output file
    filename: 'app.js',
  },
  plugins: [
    // Enables Hot Modules Replacement
    new webpack.HotModuleReplacementPlugin(),
    // Allows error warnings but does not stop compiling.
    new webpack.NoErrorsPlugin(),
    // Moves files
    new TransferWebpackPlugin([
      {from: 'www'},
    ], path.resolve(__dirname, 'src')),
  ],
  module: {
    loaders: [
      {
        test: /\.js$/, // All .js files
        loaders: ['babel-loader'],
        exclude: [nodeModulesPath],
      },
    ],
  },
};

module.exports = config;

```

Could you please help me to config ? Please more detail, I'm newbie :)

**Comment by samageloff** [comment]
Hi @luanad6365, we don't yet have a solution for your issue above. Here is an example app we've set up, that has React{ions} running: https://github.com/GetAmbassador/reactions-webpack-example. 

If you'd like, you can use this as a starting point, until we've resolved the issue above. 

- Sam

**Comment by samageloff** [comment]
Hey @luanad6365, you are missing a couple of dependencies from your `package.json` file. 

Run the following:
`npm install sass-loader style-loader --save`

Then in your **webpack config**, add the following to your **loaders** array:

```
{
      test: /\.(css|scss)$/,
      loaders: [
        'style?sourceMap',
        'css',
        'postcss',
        'sass?sourceMap'
      ],
      include: [
        /node_modules\/react-ions\/lib\/styles\/global/
      ]
    }
```

Let me know if this get's you a bit further!
